/* Copyright Helio Chissini de Castro, 2021.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
*/

pluginManagement {
    plugins {
        id("org.jruyi.thrift")
    }
}

rootProject.name = "sw360"

include(":couchdb-lucene")
include(":svc-attachments")
include(":src-projects")
include(":svc-health")
include(":svc-wsimport")
include(":svc-fossology")
include(":rest")
include(":svc-schedule")
include(":svc-licenseinfo")
include(":resource-server")
include(":svc-users")
include(":libraries")
include(":src-vulnerabilities")
include(":svc-licenses")
include(":src-components")
include(":src-attachments")
include(":src-moderation")
include(":src-vmcomponents")
include(":importers")
include(":svc-spdxpackageinfo")
include(":svc-components")
include(":src-users")
include(":svc-common")
include(":svc-spdxdocumentcreationinfo")
include(":src-cvesearch")
include(":svc-vendors")
include(":svc-moderation")
include(":src-packages")
include(":src-spdxdocument")
include(":log4j-osgi-support")
include(":src-search")
include(":commonIO")
include(":third-party")
include(":backend-utils")
include(":svc-vulnerabilities")
include(":src-wsimport")
include(":rest-common")
include(":src-common")
include(":http-support")
include(":svc-projects")
include(":src-health")
include(":svc-changelogs")
include(":build-configuration")
include(":svc-cvesearch")
include(":src-vendors")
include(":src-spdxpackageinfo")
include(":client")
include(":src-schedule")
include(":svc-search")
include(":clients")
include(":backend")
include(":svc-packages")
include(":src-changelogs")
include(":deps")
include(":src-licenseinfo")
include(":svc-vmcomponents")
include(":exporters")
include(":src-spdxdocumentcreationinfo")
include(":backend-svc")
include(":backend-src")
include(":src-licenses")
include(":datahandler")
include(":src-fossology")
include(":authorization-server")
include(":svc-spdxdocument")
project(":couchdb-lucene").projectDir = file("third-party/couchdb-lucene")
project(":svc-attachments").projectDir = file("backend/svc/svc-attachments")
project(":src-projects").projectDir = file("backend/src/src-projects")
project(":svc-health").projectDir = file("backend/svc/svc-health")
project(":svc-wsimport").projectDir = file("backend/svc/svc-wsimport")
project(":svc-fossology").projectDir = file("backend/svc/svc-fossology")
project(":svc-schedule").projectDir = file("backend/svc/svc-schedule")
project(":svc-licenseinfo").projectDir = file("backend/svc/svc-licenseinfo")
project(":resource-server").projectDir = file("rest/resource-server")
project(":svc-users").projectDir = file("backend/svc/svc-users")
project(":src-vulnerabilities").projectDir = file("backend/src/src-vulnerabilities")
project(":svc-licenses").projectDir = file("backend/svc/svc-licenses")
project(":src-components").projectDir = file("backend/src/src-components")
project(":src-attachments").projectDir = file("backend/src/src-attachments")
project(":src-moderation").projectDir = file("backend/src/src-moderation")
project(":src-vmcomponents").projectDir = file("backend/src/src-vmcomponents")
project(":importers").projectDir = file("libraries/importers")
project(":svc-spdxpackageinfo").projectDir = file("backend/svc/svc-spdxpackageinfo")
project(":svc-components").projectDir = file("backend/svc/svc-components")
project(":src-users").projectDir = file("backend/src/src-users")
project(":svc-common").projectDir = file("backend/svc-common")
project(":svc-spdxdocumentcreationinfo").projectDir = file("backend/svc/svc-spdxdocumentcreationinfo")
project(":src-cvesearch").projectDir = file("backend/src/src-cvesearch")
project(":svc-vendors").projectDir = file("backend/svc/svc-vendors")
project(":svc-moderation").projectDir = file("backend/svc/svc-moderation")
project(":src-packages").projectDir = file("backend/src/src-packages")
project(":src-spdxdocument").projectDir = file("backend/src/src-spdxdocument")
project(":log4j-osgi-support").projectDir = file("libraries/log4j-osgi-support")
project(":src-search").projectDir = file("backend/src/src-search")
project(":commonIO").projectDir = file("libraries/commonIO")
project(":backend-utils").projectDir = file("backend/utils")
project(":svc-vulnerabilities").projectDir = file("backend/svc/svc-vulnerabilities")
project(":src-wsimport").projectDir = file("backend/src/src-wsimport")
project(":rest-common").projectDir = file("rest/rest-common")
project(":src-common").projectDir = file("backend/src-common")
project(":http-support").projectDir = file("clients/http-support")
project(":svc-projects").projectDir = file("backend/svc/svc-projects")
project(":src-health").projectDir = file("backend/src/src-health")
project(":svc-changelogs").projectDir = file("backend/svc/svc-changelogs")
project(":svc-cvesearch").projectDir = file("backend/svc/svc-cvesearch")
project(":src-vendors").projectDir = file("backend/src/src-vendors")
project(":src-spdxpackageinfo").projectDir = file("backend/src/src-spdxpackageinfo")
project(":client").projectDir = file("clients/client")
project(":src-schedule").projectDir = file("backend/src/src-schedule")
project(":svc-search").projectDir = file("backend/svc/svc-search")
project(":svc-packages").projectDir = file("backend/svc/svc-packages")
project(":src-changelogs").projectDir = file("backend/src/src-changelogs")
project(":deps").projectDir = file("utils")
project(":src-licenseinfo").projectDir = file("backend/src/src-licenseinfo")
project(":svc-vmcomponents").projectDir = file("backend/svc/svc-vmcomponents")
project(":exporters").projectDir = file("libraries/exporters")
project(":src-spdxdocumentcreationinfo").projectDir = file("backend/src/src-spdxdocumentcreationinfo")
project(":backend-svc").projectDir = file("backend/svc")
project(":backend-src").projectDir = file("backend/src")
project(":src-licenses").projectDir = file("backend/src/src-licenses")
project(":datahandler").projectDir = file("libraries/datahandler")
project(":src-fossology").projectDir = file("backend/src/src-fossology")
project(":authorization-server").projectDir = file("rest/authorization-server")
project(":svc-spdxdocument").projectDir = file("backend/svc/svc-spdxdocument")
