/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.7.6")
    compileOnly("javax.servlet:javax.servlet-api:3.0.1")
}

description = "rest-common"
