/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api(project(":src-vulnerabilities"))
    api("com.google.code.gson:gson:2.10.1")
}

description = "src-cvesearch"
