/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("org.apache.logging.log4j:log4j-api:2.19.0")
    api("org.apache.logging.log4j:log4j-core:2.19.0")
    api("org.apache.commons:commons-csv:1.9.0")
    api(project(":datahandler"))
    api(project(":commonIO"))
    api(project(":exporters"))
    runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl:2.19.0")
    testImplementation(project(":src-components"))
    testImplementation(project(":src-vendors"))
    testImplementation(project(":src-attachments"))
    testImplementation(project(":datahandler"))
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.hamcrest:hamcrest-all:1.3")
    testImplementation("org.mockito:mockito-core:4.7.0")
}

description = "importers"
