/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api(project(":src-attachments"))
    api("commons-cli:commons-cli:1.4")
}

description = "backend-utils"
