/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("com.jcraft:jsch:0.1.54")
    api("org.springframework:spring-core:5.3.27")
    api("org.springframework:spring-beans:5.3.27")
    api("org.springframework:spring-context:5.3.27")
    api("org.springframework:spring-webmvc:5.3.27")
    api("org.springframework:spring-web:5.3.27")
    api("com.fasterxml.jackson.core:jackson-databind:2.14.2")
}

description = "src-fossology"
