/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
    war
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-actuator:2.7.6")
    api("org.springframework.boot:spring-boot-starter-web:2.7.6")
    api("org.springframework.boot:spring-boot-starter-security:2.7.6")
    api("org.springframework.boot:spring-boot-starter-data-rest:2.7.6")
    api("org.springframework.security.oauth:spring-security-oauth2:2.5.1.RELEASE")
    api("org.springframework.security:spring-security-jwt:1.1.1.RELEASE")
    api("org.projectlombok:lombok:1.18.24")
    api("org.springframework.data:spring-data-rest-hal-explorer:3.7.6")
    api("org.apache.thrift:libthrift:0.16.0")
    api("org.springframework:spring-webmvc:5.3.27")
    api(project(":commonIO"))
    api(project(":rest-common"))
    api("jakarta.xml.bind:jakarta.xml.bind-api:2.3.2")
    api("org.glassfish.jaxb:jaxb-runtime:2.3.2")
    api("javax.annotation:javax.annotation-api:1.3.2")
    api("javax.activation:activation:1.1.1")
    api("org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.6.6")
    api("org.bitbucket.b_c:jose4j:0.9.3")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.6")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.springframework.security:spring-security-test:5.7.5")
    testImplementation("org.springframework.restdocs:spring-restdocs-mockmvc:2.0.6.RELEASE")
    providedCompile("org.springframework.boot:spring-boot-starter-tomcat:2.7.6")
}

description = "resource-server"
