/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api(project(":src-vulnerabilities"))
    api("com.github.tomakehurst:wiremock:1.58")
    api("org.apache.httpcomponents:httpcore:4.4.4")
}

description = "src-vmcomponents"
