/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("com.google.code.gson:gson:2.10.1")
    api("com.github.cliftonlabs:json-simple:2.3.1")
}

description = "src-wsimport"
