/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api(project(":http-support"))
    api("org.slf4j:slf4j-api:1.7.30")
    api("com.fasterxml.jackson.core:jackson-core:2.14.2")
    api("com.fasterxml.jackson.core:jackson-databind:2.14.2")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("commons-io:commons-io:2.11.0")
    api("com.github.package-url:packageurl-java:1.4.1")
    testImplementation("org.assertj:assertj-core:3.11.1")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.mockito:mockito-core:2.28.2")
    testImplementation("net.bytebuddy:byte-buddy:1.10.18")
    testImplementation("org.ow2.asm:asm:7.1")
    testImplementation("org.ow2.asm:asm-util:7.1")
    testImplementation("org.ow2.asm:asm-commons:7.1")
    testImplementation("nl.jqno.equalsverifier:equalsverifier:3.1.12")
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.26.0")
    testImplementation("javax.servlet:javax.servlet-api:4.0.1")
}

description = "client"
