/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("org.apache.httpcomponents:httpmime:4.3.3")
    api("org.spdx:tools-java:1.1.5")
    api("org.apache.logging.log4j:log4j-1.2-api:2.19.0")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("org.cyclonedx:cyclonedx-core-java:7.3.2")
    api("com.github.package-url:packageurl-java:1.4.1")
}

description = "src-common"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
