/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api(project(":src-attachments"))
    api("org.spdx:tools-java:1.1.5")
    api("org.apache.logging.log4j:log4j-1.2-api:2.19.0")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("org.apache.velocity:velocity-engine-core:2.3")
    api("org.apache.velocity.tools:velocity-tools-generic:3.1")
    api("org.apache.poi:poi:4.1.2")
    api("org.apache.poi:poi-ooxml:4.1.2")
    api("net.sf.saxon:saxon-dom:8.7")
    testImplementation("com.tngtech.java:junit-dataprovider:1.13.1")
    testImplementation("org.dom4j:dom4j:2.1.3")
    testImplementation("jaxen:jaxen:1.1.6")
}

description = "src-licenseinfo"
