/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("org.apache.logging.log4j:log4j-1.2-api:2.19.0")
    api("org.apache.commons:commons-lang3:3.12.0")
    api(project(":src-spdxdocument"))
}

description = "src-spdxpackageinfo"
