/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("org.spdx:tools-java:1.1.5")
    api("org.apache.logging.log4j:log4j-1.2-api:2.19.0")
    api("org.apache.commons:commons-lang3:3.12.0")
    compileOnly("com.liferay:com.liferay.petra.function:5.1.2")
}

description = "src-licenses"
