/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api(project(":datahandler"))
    api(project(":commonIO"))
    api("org.apache.commons:commons-csv:1.9.0")
    api("org.apache.logging.log4j:log4j-api:2.19.0")
    api("org.apache.logging.log4j:log4j-core:2.19.0")
    api("org.jetbrains:annotations:15.0")
    api("org.slf4j:slf4j-api:1.7.30")
    api("com.google.guava:guava:32.0.0-jre")
    api("org.apache.poi:poi-ooxml:4.1.2")
    runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl:2.19.0")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.hamcrest:hamcrest-all:1.3")
    testImplementation("org.mockito:mockito-core:4.7.0")
}

description = "exporters"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
