/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
    war
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.7.6")
    api("org.springframework.boot:spring-boot-starter-security:2.7.6")
    api("org.springframework.security.oauth:spring-security-oauth2:2.5.1.RELEASE")
    api("org.springframework.security:spring-security-jwt:1.1.1.RELEASE")
    api("jakarta.xml.bind:jakarta.xml.bind-api:2.3.2")
    api("org.glassfish.jaxb:jaxb-runtime:2.3.2")
    api("javax.annotation:javax.annotation-api:1.3.2")
    api(project(":rest-common"))
    api("org.springframework.security:spring-security-core:5.7.5")
    api("org.ektorp:org.ektorp:1.5.0")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.6")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.springframework.security:spring-security-test:5.7.5")
    testImplementation("org.springframework.restdocs:spring-restdocs-core:2.0.6.RELEASE")
    testImplementation("org.springframework.restdocs:spring-restdocs-mockmvc:2.0.6.RELEASE")
    providedCompile("org.springframework.boot:spring-boot-starter-tomcat:2.7.6")
    providedCompile("org.projectlombok:lombok:1.18.24")
    providedCompile("javax.servlet:javax.servlet-api:3.0.1")
}

description = "authorization-server"
