/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.eclipse.sw360.java-conventions")
}

dependencies {
    api("com.opencsv:opencsv:5.5.2")
}

description = "src-users"
